# Generated by Django 5.1.3 on 2024-11-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0008_usuariofavorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioFavorito',
        ),
    ]
